/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Sara Hassane
 */
public class theFrameOfTheInvoice extends javax.swing.JFrame {

    /**
     * Creates new form theFrameOfTheInvoice
     */
    public theFrameOfTheInvoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        theInvoiceTable = new javax.swing.JTable();
        createNewInvoice_Button = new javax.swing.JButton();
        deleteInvoice_Button = new javax.swing.JButton();
        theInvoiceNumber_label_static = new javax.swing.JLabel();
        theInvoiceDate_label_static = new javax.swing.JLabel();
        theCustomerName_label_static = new javax.swing.JLabel();
        theInvoiceTotal_label_static = new javax.swing.JLabel();
        theInvoiceNumber_label = new javax.swing.JLabel();
        theInvoiceDate_label = new javax.swing.JLabel();
        theCustomerName_label = new javax.swing.JLabel();
        theInvoiceTotal_label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        theDataTable = new javax.swing.JTable();
        theSave_Button = new javax.swing.JButton();
        theCancel_Button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadFile_menuItem = new javax.swing.JMenuItem();
        saveFile_menuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        theInvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(theInvoiceTable);

        createNewInvoice_Button.setText("Create New Invoice");
        createNewInvoice_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewInvoice_ButtonActionPerformed(evt);
            }
        });

        deleteInvoice_Button.setText("Delete Invoice");

        theInvoiceNumber_label_static.setText("Invoice Number");

        theInvoiceDate_label_static.setText("Invoice Date");

        theCustomerName_label_static.setText("Customer Name");

        theInvoiceTotal_label_static.setText("Invoice Total");

        theDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(theDataTable);

        theSave_Button.setText("Save");
        theSave_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theSave_ButtonActionPerformed(evt);
            }
        });

        theCancel_Button.setText("Cancel");

        jMenu1.setText("File");

        loadFile_menuItem.setText("Load File");
        loadFile_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFile_menuItemActionPerformed(evt);
            }
        });
        jMenu1.add(loadFile_menuItem);

        saveFile_menuItem.setText("Save File");
        saveFile_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFile_menuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveFile_menuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(createNewInvoice_Button)
                        .addGap(56, 56, 56)
                        .addComponent(deleteInvoice_Button)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(theInvoiceNumber_label_static)
                                    .addComponent(theInvoiceDate_label_static)
                                    .addComponent(theCustomerName_label_static)
                                    .addComponent(theInvoiceTotal_label_static))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(theInvoiceTotal_label)
                                    .addComponent(theCustomerName_label)
                                    .addComponent(theInvoiceDate_label)
                                    .addComponent(theInvoiceNumber_label))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(theSave_Button)
                        .addGap(106, 106, 106)
                        .addComponent(theCancel_Button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(theInvoiceNumber_label_static)
                            .addComponent(theInvoiceNumber_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(theInvoiceDate_label_static)
                            .addComponent(theInvoiceDate_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(theCustomerName_label_static)
                            .addComponent(theCustomerName_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(theInvoiceTotal_label_static)
                            .addComponent(theInvoiceTotal_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewInvoice_Button)
                    .addComponent(deleteInvoice_Button)
                    .addComponent(theSave_Button)
                    .addComponent(theCancel_Button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void theSave_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theSave_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_theSave_ButtonActionPerformed

    private void loadFile_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFile_menuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadFile_menuItemActionPerformed

    private void saveFile_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFile_menuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveFile_menuItemActionPerformed

    private void createNewInvoice_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewInvoice_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createNewInvoice_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(theFrameOfTheInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(theFrameOfTheInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(theFrameOfTheInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(theFrameOfTheInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new theFrameOfTheInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewInvoice_Button;
    private javax.swing.JButton deleteInvoice_Button;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadFile_menuItem;
    private javax.swing.JMenuItem saveFile_menuItem;
    private javax.swing.JButton theCancel_Button;
    private javax.swing.JLabel theCustomerName_label;
    private javax.swing.JLabel theCustomerName_label_static;
    private javax.swing.JTable theDataTable;
    private javax.swing.JLabel theInvoiceDate_label;
    private javax.swing.JLabel theInvoiceDate_label_static;
    private javax.swing.JLabel theInvoiceNumber_label;
    private javax.swing.JLabel theInvoiceNumber_label_static;
    private javax.swing.JTable theInvoiceTable;
    private javax.swing.JLabel theInvoiceTotal_label;
    private javax.swing.JLabel theInvoiceTotal_label_static;
    private javax.swing.JButton theSave_Button;
    // End of variables declaration//GEN-END:variables
}
